CC=clang
BUILD_DIR=dist
CFLAGS=-O2 -Wall -Wextra -Werror

.PHONY: clean web all

all: web

clean:
	rm -rf $(BUILD_DIR)

$(BUILD_DIR):
	mkdir -p $(BUILD_DIR)

WEB_DIR=src/web
TETRIS_DIR = src/tetris
TETRIS_HDR = $(TETRIS_DIR)/tetris.h
TETRIS_SRC = $(WEB_DIR)/tetris.c
WEB_FILES = $(wildcard $(WEB_DIR)/*.html) $(wildcard $(WEB_DIR)/*.js)
TETRIS_WASM = $(BUILD_DIR)/tetris.wasm
WEB_CFLAGS = -target wasm32 -nostdlib -Wl,--export-all -Wl,--allow-undefined -Wl,--no-entry -I$(TETRIS_DIR)

$(BUILD_DIR)/tetris.wasm: $(TETRIS_HDR) $(TETRIS_SRC) | $(BUILD_DIR)
	clang $(CFLAGS) $(WEB_CFLAGS) $(TETRIS_SRC) -o $(BUILD_DIR)/tetris.wasm

web: $(TETRIS_WASM) | $(BUILD_DIR)
	cp $(WEB_FILES) $(BUILD_DIR)
